/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demoWebApp;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        HelloServlet classUnderTest = new HelloServlet();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest);
    }
}
